#include "Assets.h"
#include "NSEngine.h"

int gameassets::tex_ascii;
int gameassets::se_alert;
int gameassets::se_bonus2;
int gameassets::se_bonus;
int gameassets::se_boon00;
int gameassets::se_boon01;
int gameassets::se_cancel00;
int gameassets::se_cardget;
int gameassets::se_cat00;
int gameassets::se_cat01;
int gameassets::se_ch00;
int gameassets::se_ch01;
int gameassets::se_ch02;
int gameassets::se_damage00;
int gameassets::se_damage01;
int gameassets::se_enep00;
int gameassets::se_enep01;
int gameassets::se_enep02;
int gameassets::se_extend;
int gameassets::se_graze;
int gameassets::se_gun00;
int gameassets::se_hint00;
int gameassets::se_invalid;
int gameassets::se_item00;
int gameassets::se_kira00;
int gameassets::se_kira01;
int gameassets::se_kira02;
int gameassets::se_lazer00;
int gameassets::se_lazer01;
int gameassets::se_msl;
int gameassets::se_nep00;
int gameassets::se_ok00;
int gameassets::se_option;
int gameassets::se_pause;
int gameassets::se_pldead00;
int gameassets::se_plst00;
int gameassets::se_power0;
int gameassets::se_power1;
int gameassets::se_powerup;
int gameassets::se_select00;
int gameassets::se_slash;
int gameassets::se_tan00;
int gameassets::se_tan01;
int gameassets::se_tan02;
int gameassets::se_timeout2;
int gameassets::se_timeout;
int gameassets::se_warpl;
int gameassets::se_warpr;
int gameassets::se_water;
int gameassets::fnt_base;
int gameassets::fnt_small;
int gameassets::fnt_score;
int gameassets::fnt_bignumbers;
int gameassets::fnt_score2;
int gameassets::fnt_pickup1;
int gameassets::fnt_pickup2;
int gameassets::fnt_pickup3;
int gameassets::mus_st01;
int gameassets::mus_st01bs;

int defaultTexID;
int defaultTexture() { return defaultTexID; }
int defaultFontID;
int defaultFont() { return defaultFontID; }

void gameassets::Init()
{
    defaultTexID = NSEngine::TextureManager::RegisterTexture(        "assets/engine/textures/defaultTexture.png");
    defaultFontID = NSEngine::SpriteManager::RegisterFont(        "assets/engine/fonts/Lato-Regular.ttf, 10");
    tex_ascii = NSEngine::TextureManager::            RegisterTexture("assets/textures/ascii/ascii.png", "assets/textures/ascii/ascii_960.png", "assets/textures/ascii/ascii_1280.png");
    se_alert = NSEngine::AudioEngine::            AddSFX("assets/sounds/se_alert.wav");
    se_bonus2 = NSEngine::AudioEngine::            AddSFX("assets/sounds/se_bonus2.wav");
    se_bonus = NSEngine::AudioEngine::            AddSFX("assets/sounds/se_bonus.wav");
    se_boon00 = NSEngine::AudioEngine::            AddSFX("assets/sounds/se_boon00.wav");
    se_boon01 = NSEngine::AudioEngine::            AddSFX("assets/sounds/se_boon01.wav");
    se_cancel00 = NSEngine::AudioEngine::            AddSFX("assets/sounds/se_cancel00.wav");
    se_cardget = NSEngine::AudioEngine::            AddSFX("assets/sounds/se_cardget.wav");
    se_cat00 = NSEngine::AudioEngine::            AddSFX("assets/sounds/se_cat00.wav");
    se_cat01 = NSEngine::AudioEngine::            AddSFX("assets/sounds/se_cat01.wav");
    se_ch00 = NSEngine::AudioEngine::            AddSFX("assets/sounds/se_ch00.wav");
    se_ch01 = NSEngine::AudioEngine::            AddSFX("assets/sounds/se_ch01.wav");
    se_ch02 = NSEngine::AudioEngine::            AddSFX("assets/sounds/se_ch02.wav");
    se_damage00 = NSEngine::AudioEngine::            AddSFX("assets/sounds/se_damage00.wav");
    se_damage01 = NSEngine::AudioEngine::            AddSFX("assets/sounds/se_damage01.wav");
    se_enep00 = NSEngine::AudioEngine::            AddSFX("assets/sounds/se_enep00.wav");
    se_enep01 = NSEngine::AudioEngine::            AddSFX("assets/sounds/se_enep01.wav");
    se_enep02 = NSEngine::AudioEngine::            AddSFX("assets/sounds/se_enep02.wav");
    se_extend = NSEngine::AudioEngine::            AddSFX("assets/sounds/se_extend.wav");
    se_graze = NSEngine::AudioEngine::            AddSFX("assets/sounds/se_graze.wav");
    se_gun00 = NSEngine::AudioEngine::            AddSFX("assets/sounds/se_gun00.wav");
    se_hint00 = NSEngine::AudioEngine::            AddSFX("assets/sounds/se_hint00.wav");
    se_invalid = NSEngine::AudioEngine::            AddSFX("assets/sounds/se_invalid.wav");
    se_item00 = NSEngine::AudioEngine::            AddSFX("assets/sounds/se_item00.wav");
    se_kira00 = NSEngine::AudioEngine::            AddSFX("assets/sounds/se_kira00.wav");
    se_kira01 = NSEngine::AudioEngine::            AddSFX("assets/sounds/se_kira01.wav");
    se_kira02 = NSEngine::AudioEngine::            AddSFX("assets/sounds/se_kira02.wav");
    se_lazer00 = NSEngine::AudioEngine::            AddSFX("assets/sounds/se_lazer00.wav");
    se_lazer01 = NSEngine::AudioEngine::            AddSFX("assets/sounds/se_lazer01.wav");
    se_msl = NSEngine::AudioEngine::            AddSFX("assets/sounds/se_msl.wav");
    se_nep00 = NSEngine::AudioEngine::            AddSFX("assets/sounds/se_nep00.wav");
    se_ok00 = NSEngine::AudioEngine::            AddSFX("assets/sounds/se_ok00.wav");
    se_option = NSEngine::AudioEngine::            AddSFX("assets/sounds/se_option.wav");
    se_pause = NSEngine::AudioEngine::            AddSFX("assets/sounds/se_pause.wav");
    se_pldead00 = NSEngine::AudioEngine::            AddSFX("assets/sounds/se_pldead00.wav");
    se_plst00 = NSEngine::AudioEngine::            AddSFX("assets/sounds/se_plst00.wav");
    se_power0 = NSEngine::AudioEngine::            AddSFX("assets/sounds/se_power0.wav");
    se_power1 = NSEngine::AudioEngine::            AddSFX("assets/sounds/se_power1.wav");
    se_powerup = NSEngine::AudioEngine::            AddSFX("assets/sounds/se_powerup.wav");
    se_select00 = NSEngine::AudioEngine::            AddSFX("assets/sounds/se_select00.wav");
    se_slash = NSEngine::AudioEngine::            AddSFX("assets/sounds/se_slash.wav");
    se_tan00 = NSEngine::AudioEngine::            AddSFX("assets/sounds/se_tan00.wav");
    se_tan01 = NSEngine::AudioEngine::            AddSFX("assets/sounds/se_tan01.wav");
    se_tan02 = NSEngine::AudioEngine::            AddSFX("assets/sounds/se_tan02.wav");
    se_timeout2 = NSEngine::AudioEngine::            AddSFX("assets/sounds/se_timeout2.wav");
    se_timeout = NSEngine::AudioEngine::            AddSFX("assets/sounds/se_timeout.wav");
    se_warpl = NSEngine::AudioEngine::            AddSFX("assets/sounds/se_warpl.wav");
    se_warpr = NSEngine::AudioEngine::            AddSFX("assets/sounds/se_warpr.wav");
    se_water = NSEngine::AudioEngine::            AddSFX("assets/sounds/se_water.wav");
    fnt_base = NSEngine::SpriteManager::            RegisterFont(tex_ascii, 14, 14, " !\"#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\\]^_`abcdefghijklmnopqrstuvwxyz{|}~£¬", 98, 0, 0, 0);
    fnt_small = NSEngine::SpriteManager::            RegisterFont(tex_ascii, 8, 8, " !\"#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\\]^_`abcdefghijklmnopqrstuvwxyz{|}~£¬", 98, 0, 88, 0);
    fnt_score = NSEngine::SpriteManager::            RegisterFont(tex_ascii, 8, 9, " 0123456789/+-x%.+ABCDEFGHIJKLMNOPQRSTUVWXYZ", 45, 0, 160, 0);
    fnt_bignumbers = NSEngine::SpriteManager::            RegisterFont(tex_ascii, 16, 16, " 0123456789/.sx,", 17, 0, 144, -4);
    fnt_score2 = NSEngine::SpriteManager::            RegisterFont("assets/fonts/fontScore.fnt");
    fnt_pickup1 = NSEngine::SpriteManager::            RegisterFont("assets/fonts/fontPickup.fnt");
    fnt_pickup2 = NSEngine::SpriteManager::            RegisterFont("assets/fonts/fontPickup1.fnt");
    fnt_pickup3 = NSEngine::SpriteManager::            RegisterFont("assets/fonts/fontPickup2.fnt");
    mus_st01 = NSEngine::AudioEngine::            AddMusic("assets/musics/TH16_02.wav");
    mus_st01bs = NSEngine::AudioEngine::            AddMusic("assets/musics/TH16_03.wav");
}