#define NSK_0 SDLK_0
#define NSK_1 SDLK_1
#define NSK_2 SDLK_2
#define NSK_3 SDLK_3
#define NSK_4 SDLK_4
#define NSK_5 SDLK_5
#define NSK_6 SDLK_6
#define NSK_7 SDLK_7
#define NSK_8 SDLK_8
#define NSK_9 SDLK_9
#define NSK_a SDLK_a
#define NSK_acback SDLK_AC_BACK
#define NSK_acbookmarks SDLK_AC_BOOKMARKS
#define NSK_acforward SDLK_AC_FORWARD
#define NSK_achome SDLK_AC_HOME
#define NSK_acrefresh SDLK_AC_REFRESH
#define NSK_acsearch SDLK_AC_SEARCH
#define NSK_acstop SDLK_AC_STOP
#define NSK_again SDLK_AGAIN
#define NSK_alterase SDLK_ALTERASE
#define NSK_quote SDLK_QUOTE
#define NSK_application SDLK_APPLICATION
#define NSK_audiomute SDLK_AUDIOMUTE
#define NSK_audionext SDLK_AUDIONEXT
#define NSK_audioplay SDLK_AUDIOPLAY
#define NSK_audioprev SDLK_AUDIOPREV
#define NSK_audiostop SDLK_AUDIOSTOP
#define NSK_b SDLK_b
#define NSK_backslash SDLK_BACKSLASH
#define NSK_backspace SDLK_BACKSPACE
#define NSK_brightnessdown SDLK_BRIGHTNESSDOWN
#define NSK_brightnessup SDLK_BRIGHTNESSUP
#define NSK_c SDLK_c
#define NSK_calculator SDLK_CALCULATOR
#define NSK_cancel SDLK_CANCEL
#define NSK_capslock SDLK_CAPSLOCK
#define NSK_clear SDLK_CLEAR
#define NSK_clearagain SDLK_CLEARAGAIN
#define NSK_comma SDLK_COMMA
#define NSK_computer SDLK_COMPUTER
#define NSK_copy SDLK_COPY
#define NSK_crsel SDLK_CRSEL
#define NSK_currencysubunit SDLK_CURRENCYSUBUNIT
#define NSK_currencyunit SDLK_CURRENCYUNIT
#define NSK_cut SDLK_CUT
#define NSK_d SDLK_d
#define NSK_decimalseparator SDLK_DECIMALSEPARATOR
#define NSK_delete SDLK_DELETE
#define NSK_displayswitch SDLK_DISPLAYSWITCH
#define NSK_down SDLK_DOWN
#define NSK_e SDLK_e
#define NSK_eject SDLK_EJECT
#define NSK_end SDLK_END
#define NSK_equals SDLK_EQUALS
#define NSK_escape SDLK_ESCAPE
#define NSK_execute SDLK_EXECUTE
#define NSK_exsel SDLK_EXSEL
#define NSK_f SDLK_f
#define NSK_f1 SDLK_F1
#define NSK_f10 SDLK_F10
#define NSK_f11 SDLK_F11
#define NSK_f12 SDLK_F12
#define NSK_f13 SDLK_F13
#define NSK_f14 SDLK_F14
#define NSK_f15 SDLK_F15
#define NSK_f16 SDLK_F16
#define NSK_f17 SDLK_F17
#define NSK_f18 SDLK_F18
#define NSK_f19 SDLK_F19
#define NSK_f2 SDLK_F2
#define NSK_f20 SDLK_F20
#define NSK_f21 SDLK_F21
#define NSK_f22 SDLK_F22
#define NSK_f23 SDLK_F23
#define NSK_f24 SDLK_F24
#define NSK_f3 SDLK_F3
#define NSK_f4 SDLK_F4
#define NSK_f5 SDLK_F5
#define NSK_f6 SDLK_F6
#define NSK_f7 SDLK_F7
#define NSK_f8 SDLK_F8
#define NSK_f9 SDLK_F9
#define NSK_find SDLK_FIND
#define NSK_g SDLK_g
#define NSK_backquote SDLK_BACKQUOTE
#define NSK_h SDLK_h
#define NSK_help SDLK_HELP
#define NSK_home SDLK_HOME
#define NSK_i SDLK_i
#define NSK_insert SDLK_INSERT
#define NSK_j SDLK_j
#define NSK_k SDLK_k
#define NSK_kbdillumdown SDLK_KBDILLUMDOWN
#define NSK_kbdillumtoggle SDLK_KBDILLUMTOGGLE
#define NSK_kbdillumup SDLK_KBDILLUMUP
#define NSK_kp0 SDLK_KP_0
#define NSK_kp00 SDLK_KP_00
#define NSK_kp000 SDLK_KP_000
#define NSK_kp1 SDLK_KP_1
#define NSK_kp2 SDLK_KP_2
#define NSK_kp3 SDLK_KP_3
#define NSK_kp4 SDLK_KP_4
#define NSK_kp5 SDLK_KP_5
#define NSK_kp6 SDLK_KP_6
#define NSK_kp7 SDLK_KP_7
#define NSK_kp8 SDLK_KP_8
#define NSK_kp9 SDLK_KP_9
#define NSK_kpa SDLK_KP_A
#define NSK_kpampersand SDLK_KP_AMPERSAND
#define NSK_kpat SDLK_KP_AT
#define NSK_kpb SDLK_KP_B
#define NSK_kpbackspace SDLK_KP_BACKSPACE
#define NSK_kpbinary SDLK_KP_BINARY
#define NSK_kpc SDLK_KP_C
#define NSK_kpclear SDLK_KP_CLEAR
#define NSK_kpclearentry SDLK_KP_CLEARENTRY
#define NSK_kpcolon SDLK_KP_COLON
#define NSK_kpcomma SDLK_KP_COMMA
#define NSK_kpd SDLK_KP_D
#define NSK_kpdblampersand SDLK_KP_DBLAMPERSAND
#define NSK_kpdblverticalbar SDLK_KP_DBLVERTICALBAR
#define NSK_kpdecimal SDLK_KP_DECIMAL
#define NSK_kpdivide SDLK_KP_DIVIDE
#define NSK_kpe SDLK_KP_E
#define NSK_kpenter SDLK_KP_ENTER
#define NSK_kpequals SDLK_KP_EQUALS
#define NSK_kpequalsas400 SDLK_KP_EQUALSAS400
#define NSK_kpexclam SDLK_KP_EXCLAM
#define NSK_kpf SDLK_KP_F
#define NSK_kpgreater SDLK_KP_GREATER
#define NSK_kphash SDLK_KP_HASH
#define NSK_kphexadecimal SDLK_KP_HEXADECIMAL
#define NSK_kpleftbrace SDLK_KP_LEFTBRACE
#define NSK_kpleftparen SDLK_KP_LEFTPAREN
#define NSK_kpless SDLK_KP_LESS
#define NSK_kpmemadd SDLK_KP_MEMADD
#define NSK_kpmemclear SDLK_KP_MEMCLEAR
#define NSK_kpmemdivide SDLK_KP_MEMDIVIDE
#define NSK_kpmemmultiply SDLK_KP_MEMMULTIPLY
#define NSK_kpmemrecall SDLK_KP_MEMRECALL
#define NSK_kpmemstore SDLK_KP_MEMSTORE
#define NSK_kpmemsubtract SDLK_KP_MEMSUBTRACT
#define NSK_kpminus SDLK_KP_MINUS
#define NSK_kpmultiply SDLK_KP_MULTIPLY
#define NSK_kpoctal SDLK_KP_OCTAL
#define NSK_kppercent SDLK_KP_PERCENT
#define NSK_kpperiod SDLK_KP_PERIOD
#define NSK_kpplus SDLK_KP_PLUS
#define NSK_kpplusminus SDLK_KP_PLUSMINUS
#define NSK_kppower SDLK_KP_POWER
#define NSK_kprightbrace SDLK_KP_RIGHTBRACE
#define NSK_kprightparen SDLK_KP_RIGHTPAREN
#define NSK_kpspace SDLK_KP_SPACE
#define NSK_kptab SDLK_KP_TAB
#define NSK_kpverticalbar SDLK_KP_VERTICALBAR
#define NSK_kpxor SDLK_KP_XOR
#define NSK_l SDLK_l
#define NSK_lalt SDLK_LALT
#define NSK_lctrl SDLK_LCTRL
#define NSK_left SDLK_LEFT
#define NSK_leftbracket SDLK_LEFTBRACKET
#define NSK_lgui SDLK_LGUI
#define NSK_lshift SDLK_LSHIFT
#define NSK_m SDLK_m
#define NSK_mail SDLK_MAIL
#define NSK_mediaselect SDLK_MEDIASELECT
#define NSK_menu SDLK_MENU
#define NSK_minus SDLK_MINUS
#define NSK_mode SDLK_MODE
#define NSK_mute SDLK_MUTE
#define NSK_n SDLK_n
#define NSK_numlockclear SDLK_NUMLOCKCLEAR
#define NSK_o SDLK_o
#define NSK_oper SDLK_OPER
#define NSK_out SDLK_OUT
#define NSK_p SDLK_p
#define NSK_pagedown SDLK_PAGEDOWN
#define NSK_pageup SDLK_PAGEUP
#define NSK_paste SDLK_PASTE
#define NSK_pause SDLK_PAUSE
#define NSK_period SDLK_PERIOD
#define NSK_power SDLK_POWER
#define NSK_printscreen SDLK_PRINTSCREEN
#define NSK_prior SDLK_PRIOR
#define NSK_q SDLK_q
#define NSK_r SDLK_r
#define NSK_ralt SDLK_RALT
#define NSK_rctrl SDLK_RCTRL
#define NSK_return SDLK_RETURN
#define NSK_return2 SDLK_RETURN2
#define NSK_rgui SDLK_RGUI
#define NSK_right SDLK_RIGHT
#define NSK_rightbracket SDLK_RIGHTBRACKET
#define NSK_rshift SDLK_RSHIFT
#define NSK_s SDLK_s
#define NSK_scrolllock SDLK_SCROLLLOCK
#define NSK_select SDLK_SELECT
#define NSK_semicolon SDLK_SEMICOLON
#define NSK_separator SDLK_SEPARATOR
#define NSK_slash SDLK_SLASH
#define NSK_sleep SDLK_SLEEP
#define NSK_space SDLK_SPACE
#define NSK_stop SDLK_STOP
#define NSK_sysreq SDLK_SYSREQ
#define NSK_t SDLK_t
#define NSK_tab SDLK_TAB
#define NSK_thousandsseparator SDLK_THOUSANDSSEPARATOR
#define NSK_u SDLK_u
#define NSK_undo SDLK_UNDO
#define NSK_unknown SDLK_UNKNOWN
#define NSK_up SDLK_UP
#define NSK_v SDLK_v
#define NSK_volumedown SDLK_VOLUMEDOWN
#define NSK_volumeup SDLK_VOLUMEUP
#define NSK_w SDLK_w
#define NSK_www SDLK_WWW
#define NSK_x SDLK_x
#define NSK_y SDLK_y
#define NSK_z SDLK_z
#define NSK_ampersand SDLK_AMPERSAND
#define NSK_asterisk SDLK_ASTERISK
#define NSK_at SDLK_AT
#define NSK_caret SDLK_CARET
#define NSK_colon SDLK_COLON
#define NSK_dollar SDLK_DOLLAR
#define NSK_exclaim SDLK_EXCLAIM
#define NSK_greater SDLK_GREATER
#define NSK_hash SDLK_HASH
#define NSK_leftparen SDLK_LEFTPAREN
#define NSK_less SDLK_LESS
#define NSK_percent SDLK_PERCENT
#define NSK_plus SDLK_PLUS
#define NSK_question SDLK_QUESTION
#define NSK_quotedbl SDLK_QUOTEDBL
#define NSK_rightparen SDLK_RIGHTPAREN
#define NSK_underscores SDLK_UNDERSCORES

#define NSM_leftclick SDL_BUTTON_LEFT
#define NSM_rightclick SDL_BUTTON_RIGHT
#define NSM_middleclick SDL_BUTTON_MIDDLE
#define NSM_x1click SDL_BUTTON_X1
#define NSM_x2click SDL_BUTTON_X2

#define NS_CURSOR_ARROW 0
#define NS_CURSOR_IBEAM 1
#define NS_CURSOR_WAIT 2
#define NS_CURSOR_CROSSHAIR 3
#define NS_CURSOR_WAITARROW 4
#define NS_CURSOR_SIZEDTL 5
#define NS_CURSOR_SIZEDTR 6
#define NS_CURSOR_SIZEHOR 7
#define NS_CURSOR_SIZEVER 8
#define NS_CURSOR_SIZEALL 9
#define NS_CURSOR_NO 10
#define NS_CURSOR_HAND 11
